// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           16
// Async Callback (empty):               1
// Total number of exported functions:  18

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    stacktoken
    (
        init => init
        postQuestion => post_question
        submitAnswer => submit_answer
        approveAnswer => approve_answer
        refundQuestion => refund_question
        expireQuestions => expire_questions
        getAllOpenQuestions => get_all_open_questions
        getQuestionDetails => get_question_details
        getAnswersForQuestion => get_answers_for_question
        pauseContract => pause_contract
        unpauseContract => unpause_contract
        transferOwnership => transfer_ownership
        getOwner => get_owner
        isPaused => is_contract_paused
        getTotalQuestions => get_total_questions
        getTotalAnswers => get_total_answers
        getContractStats => get_contract_stats
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
