// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            9
// Async Callback (empty):               1
// Total number of exported functions:  11

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    stacktoken
    (
        init => init
        postQuestion => post_question
        submitAnswer => submit_answer
        approveAnswer => approve_answer
        refundQuestion => refund_question
        getAllOpenQuestions => get_all_open_questions
        getQuestionDetails => get_question_details
        getAnswersForQuestion => get_answers_for_question
        getQuestionsByStatus => get_questions_by_status
        getExpiredQuestions => get_expired_questions
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
